DROP TABLE IF EXISTS EXCHANGE_RATE;

CREATE TABLE EXCHANGE_RATE (
  code VARCHAR(250) NOT NULL PRIMARY KEY,
  origin_currency VARCHAR(250) NOT NULL,
  destination_currency VARCHAR(250) NOT NULL,
  amount DECIMAL DEFAULT NULL
);